version: '3.1'
services:
  mysql-demo:
    build:
      context: .
      dockerfile: MySQL-Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: waitwaitdonttellme

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  gcp-fetcher:
    build: 
        context: .
        dockerfile: Gcp-fetcher-Dockerfile
    environment: 
      - WAIT_HOSTS=mysql-demo:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=15
    depends_on:
        - mysql-demo